//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90000")]
        public float ObjectForceModifier {
            get {
                return ((float)(this["ObjectForceModifier"]));
            }
            set {
                this["ObjectForceModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public float TagForceModifier {
            get {
                return ((float)(this["TagForceModifier"]));
            }
            set {
                this["TagForceModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float TagItemRepulsionModifier {
            get {
                return ((float)(this["TagItemRepulsionModifier"]));
            }
            set {
                this["TagItemRepulsionModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public float BoundaryForceModifier {
            get {
                return ((float)(this["BoundaryForceModifier"]));
            }
            set {
                this["BoundaryForceModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public float ItemsCanvasWidth {
            get {
                return ((float)(this["ItemsCanvasWidth"]));
            }
            set {
                this["ItemsCanvasWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public float ItemsCanvasHeight {
            get {
                return ((float)(this["ItemsCanvasHeight"]));
            }
            set {
                this["ItemsCanvasHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public float TagCanvasWidth {
            get {
                return ((float)(this["TagCanvasWidth"]));
            }
            set {
                this["TagCanvasWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public float TagCanvasHeight {
            get {
                return ((float)(this["TagCanvasHeight"]));
            }
            set {
                this["TagCanvasHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public float ItemForceFieldDiameter {
            get {
                return ((float)(this["ItemForceFieldDiameter"]));
            }
            set {
                this["ItemForceFieldDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float TagForceFieldDiameter {
            get {
                return ((float)(this["TagForceFieldDiameter"]));
            }
            set {
                this["TagForceFieldDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float StandardTagAttraction {
            get {
                return ((float)(this["StandardTagAttraction"]));
            }
            set {
                this["StandardTagAttraction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float StandardTagRepulsion {
            get {
                return ((float)(this["StandardTagRepulsion"]));
            }
            set {
                this["StandardTagRepulsion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float TagSameDimensionForceModifier {
            get {
                return ((float)(this["TagSameDimensionForceModifier"]));
            }
            set {
                this["TagSameDimensionForceModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float TagSameCategoryForceModifier {
            get {
                return ((float)(this["TagSameCategoryForceModifier"]));
            }
            set {
                this["TagSameCategoryForceModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SimulationTimerIntervalMs {
            get {
                return ((int)(this["SimulationTimerIntervalMs"]));
            }
            set {
                this["SimulationTimerIntervalMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public float SelectedTagAttractionModifier {
            get {
                return ((float)(this["SelectedTagAttractionModifier"]));
            }
            set {
                this["SelectedTagAttractionModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComputeRepulsionForUnselectedTags {
            get {
                return ((bool)(this["ComputeRepulsionForUnselectedTags"]));
            }
            set {
                this["ComputeRepulsionForUnselectedTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float UnselectedTagRepulsionModifier {
            get {
                return ((float)(this["UnselectedTagRepulsionModifier"]));
            }
            set {
                this["UnselectedTagRepulsionModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DetectCollisions {
            get {
                return ((bool)(this["DetectCollisions"]));
            }
            set {
                this["DetectCollisions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CollisionDetectionIterations {
            get {
                return ((int)(this["CollisionDetectionIterations"]));
            }
            set {
                this["CollisionDetectionIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float ItemBaseSize {
            get {
                return ((float)(this["ItemBaseSize"]));
            }
            set {
                this["ItemBaseSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public float TagBaseSize {
            get {
                return ((float)(this["TagBaseSize"]));
            }
            set {
                this["TagBaseSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float CentripetalSpeed {
            get {
                return ((float)(this["CentripetalSpeed"]));
            }
            set {
                this["CentripetalSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public float MaxIntensityValue {
            get {
                return ((float)(this["MaxIntensityValue"]));
            }
            set {
                this["MaxIntensityValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short ApplicationType {
            get {
                return ((short)(this["ApplicationType"]));
            }
            set {
                this["ApplicationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LoadItemModulo {
            get {
                return ((string)(this["LoadItemModulo"]));
            }
            set {
                this["LoadItemModulo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProcessDepthOption {
            get {
                return ((int)(this["ProcessDepthOption"]));
            }
            set {
                this["ProcessDepthOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnforceEqualDataDistribution {
            get {
                return ((bool)(this["EnforceEqualDataDistribution"]));
            }
            set {
                this["EnforceEqualDataDistribution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxNumItemsPerTag {
            get {
                return ((int)(this["MaxNumItemsPerTag"]));
            }
            set {
                this["MaxNumItemsPerTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SensorAutostart {
            get {
                return ((bool)(this["SensorAutostart"]));
            }
            set {
                this["SensorAutostart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ReFlexServerAddress {
            get {
                return ((string)(this["ReFlexServerAddress"]));
            }
            set {
                this["ReFlexServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40001")]
        public int ReFlexServerPort {
            get {
                return ((int)(this["ReFlexServerPort"]));
            }
            set {
                this["ReFlexServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReFlex")]
        public string ReFlexServerEndpoint {
            get {
                return ((string)(this["ReFlexServerEndpoint"]));
            }
            set {
                this["ReFlexServerEndpoint"] = value;
            }
        }
    }
}
